### ISSUE TITLE
Support for CraftCMS 4

### ISSUE THREAD

**Issue by Siyabulela** [charliedevelopment/craft3-section-field#8]
Hi @charliedevelopment. Will this plugin eventually be compatible with Craftcms 4?

**Comment by nitech** [comment]
Did you find any other field to replace this one?

**Comment by Siyabulela** [comment]
No, I haven't been able to come across one yet.

Since the plugin hasn't received a response from its creator, charliedevelopment, I was thinking that perhaps you could consider cloning the plugin's repository and attempting to upgrade it yourself. You don't actually need to change anything. https://craftcms.com/docs/4.x/extend/updating-plugins.html#rector, do 1, 2 and 3.

**Comment by nitech** [comment]
Tbh. I have problems remembering exactly what this plugin looked like -- but could it be that this plugin does the same? (it seems so to me): 

https://plugins.craftcms.com/section-and-product-type?craft4
